import io
from typing import Optional, overload, Tuple

@overload
def hfp(fp: str=None, default_data: Optional[bytes]=None, buffer_size: Optional[int]=None) -> io.BufferedRandom: ...
@overload
def hfp(fp: bytes=None, default_data: Optional[bytes]=None, buffer_size: Optional[int]=None) -> io.BufferedRandom: ...
@overload
def hfp(fp: io.BytesIO=None, default_data: Optional[bytes]=None, buffer_size: Optional[int]=None) -> io.BufferedRandom: ...
@overload
def hfp(fp: io.BufferedRandom=None, default_data: Optional[bytes]=None, buffer_size: Optional[int]=None) -> io.BufferedRandom: ...
@overload
def hfp(fp: io.BufferedReader=None, default_data: Optional[bytes]=None, buffer_size: Optional[int]=None) -> io.BufferedRandom: ...
@overload
def hfp() -> io.BufferedRandom: ...
@overload
def htpn(value: str, part_size: int) -> bytes: ...
@overload
def htpn(value: bytes, part_size: int) -> bytes: ...